In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
# constants
con1=tf.constant(10)
con2=tf.constant(3.14)
con3=tf.constant("I am darshan")
con4=tf.constant(False)

In [3]:
print([con1,con2,con3,con4])

[<tf.Tensor 'Const:0' shape=() dtype=int32>, <tf.Tensor 'Const_1:0' shape=() dtype=float32>, <tf.Tensor 'Const_2:0' shape=() dtype=string>, <tf.Tensor 'Const_3:0' shape=() dtype=bool>]


In [4]:
sess=tf.Session()

In [5]:
sess.run([con1,con2,con3,con4])

[10, 3.14, b'I am darshan', False]

In [6]:
Add=tf.constant(20)+tf.constant(50)
Mul=tf.constant(30)*tf.constant(30)

In [7]:
sess.run([Add,Mul])

[70, 900]

In [8]:
add=tf.constant([3,4,5,6,7])+tf.constant([3,6,7,8,9])
mul=tf.constant([3,4,5,6,7])*tf.constant([3,6,7,8,9])

In [9]:
sess.run([add,mul])

[array([ 6, 10, 12, 14, 16], dtype=int32),
 array([ 9, 24, 35, 48, 63], dtype=int32)]

In [10]:
str1=tf.constant("i am ")
str2=tf.constant("darshan")

In [11]:
sess.run(str1+str2)

b'i am darshan'

In [12]:
# placeholder
a=tf.placeholder(tf.int32)
b=a*2

In [13]:
sess.run(b,feed_dict={a:[2,5,6,7]})

array([ 4, 10, 12, 14], dtype=int32)

In [14]:
str_name=tf.placeholder(tf.string)
my_name="I am"+str_name

In [15]:
sess.run(my_name,feed_dict={str_name:"Darshan"})

b'I amDarshan'

In [16]:
#variable

var1=tf.Variable([20],tf.int32)

In [17]:
init=tf.global_variables_initializer()

In [18]:
sess.run(init)

In [19]:
sess.run(var1)

array([20], dtype=int32)

In [20]:
updated_var1=tf.assign(var1,[25])

In [21]:
sess.run(updated_var1)

array([25], dtype=int32)

In [24]:
#linear model
W=tf.Variable([30],tf.int32)
b=tf.Variable([5],tf.int32)
x=tf.placeholder(tf.int32)

In [25]:
linear_model=W*x+b

In [26]:
init1=tf.global_variables_initializer()

In [27]:
sess.run(init1)

In [28]:
sess.run(linear_model,feed_dict={x:[1,2,3,4,5]})

array([ 35,  65,  95, 125, 155], dtype=int32)